version: "3.9"

networks:
  local-network:
    driver: bridge

services:
  web:
    tty: true
    stdin_open: true
    build: .
    working_dir: /app
    volumes:
      - .:/app
    environment:
      PORT: 4000
    command: bundle exec jekyll serve
    ports:
      - "4000:4000"
    networks:
      - local-network